### ISSUE TITLE
Tutorial 3 - User Class not being read in

### ISSUE THREAD

**Issue by e-lo** [Fast-Trips/fast-trips-tutorial#2]
The user class doesn't seem to be working for some reason?

**Comment by e-lo** [comment]
@lmz  - I updated notebooks so it should be cleaner now, but still having the problem.

**Comment by lmz** [comment]
Fixed here: https://github.com/MetropolitanTransportationCommission/fast-trips/commit/d4e982dfafe6c8fc2050dbcbe1fce640559e1704

**Comment by e-lo** [comment]
Confirmed fixed!
