### ISSUE TITLE
Kernel dying when running second fast-trips run with capacity

### ISSUE THREAD

**Issue by e-lo** [Fast-Trips/fast-trips-tutorial#7]
In Tutorial #2:

I```
NPUT_NETWORKS_NEW_ROUTE   = os.path.join(BASE_DIR,"tta","input","network-added-route")
OUTPUT_DIR   = os.path.join(BASE_DIR,"tta","output")
OUTPUT_FOLDER_NEW_ROUTE    = r"capacity-demand-wNewRoute"

Run.run_fasttrips(input_network_dir= INPUT_NETWORKS_NEW_ROUTE,
                  input_demand_dir = INPUT_DEMAND,
                  run_config       = RUN_CONFIG,
                  input_weights    = INPUT_WEIGHTS,
                  output_dir       = OUTPUT_DIR,
                  output_folder    = OUTPUT_FOLDER_NEW_ROUTE,
                  iters            = 3,
                  overlap_variable = "count",
                  dispersion       = 0.5,
                  capacity         = True,
                  output_pathset_per_sim_iter = True)
```

and from terminal window
```

Reading /Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/tutorial/tta/output/capacity-demand/ft_intermediate_weights.txt: [user_class] [purpose] [demand_mode_type] [demand_mode] [supply_mode_num] [weight_name] [weight_value]  => Read 7 lines
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
RAND_MAX = 2147483647
```

**Comment by lmz** [comment]
I added a reset state to clear out all network state proactively -- it runs for me now.

**Comment by e-lo** [comment]
Fixed!
